// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ZcQrnmrsisUCjywsfEYn4pR69PZCrpE',
    appId: '1:646915822892:web:1f32cb169f9d401e554889',
    messagingSenderId: '646915822892',
    projectId: 'pebo-task-manager-767f3',
    authDomain: 'pebo-task-manager-767f3.firebaseapp.com',
    databaseURL: 'https://pebo-task-manager-767f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pebo-task-manager-767f3.firebasestorage.app',
    measurementId: 'G-R0K2JBF6FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrrVuqcY2dGURCq5_OoyVpqqsCAcmuBzM',
    appId: '1:646915822892:android:f6ee27c15832bd4d554889',
    messagingSenderId: '646915822892',
    projectId: 'pebo-task-manager-767f3',
    databaseURL: 'https://pebo-task-manager-767f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pebo-task-manager-767f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFShmvfxluFtqhyTD3y0DlOKEAQqwOumA',
    appId: '1:646915822892:ios:9c754ce3375aa5c1554889',
    messagingSenderId: '646915822892',
    projectId: 'pebo-task-manager-767f3',
    databaseURL: 'https://pebo-task-manager-767f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pebo-task-manager-767f3.firebasestorage.app',
    iosClientId: '646915822892-d9olsa52q8ga8s4gh3oale5q2gov68ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFShmvfxluFtqhyTD3y0DlOKEAQqwOumA',
    appId: '1:646915822892:ios:9c754ce3375aa5c1554889',
    messagingSenderId: '646915822892',
    projectId: 'pebo-task-manager-767f3',
    databaseURL: 'https://pebo-task-manager-767f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pebo-task-manager-767f3.firebasestorage.app',
    iosClientId: '646915822892-d9olsa52q8ga8s4gh3oale5q2gov68ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2ZcQrnmrsisUCjywsfEYn4pR69PZCrpE',
    appId: '1:646915822892:web:7c917b279a338f78554889',
    messagingSenderId: '646915822892',
    projectId: 'pebo-task-manager-767f3',
    authDomain: 'pebo-task-manager-767f3.firebaseapp.com',
    databaseURL: 'https://pebo-task-manager-767f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pebo-task-manager-767f3.firebasestorage.app',
    measurementId: 'G-M8B04G5Q2R',
  );

}