// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ZcQrnmrsisUCjywsfEYn4pR69PZCrpE',
    appId: '1:646915822892:web:d9488e3066fcac3a554889',
    messagingSenderId: '646915822892',
    projectId: 'pebo-task-manager-767f3',
    authDomain: 'pebo-task-manager-767f3.firebaseapp.com',
    databaseURL: 'https://pebo-task-manager-767f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pebo-task-manager-767f3.firebasestorage.app',
    measurementId: 'G-4T4QX9R1TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrrVuqcY2dGURCq5_OoyVpqqsCAcmuBzM',
    appId: '1:646915822892:android:ed04bfd5bc17c9db554889',
    messagingSenderId: '646915822892',
    projectId: 'pebo-task-manager-767f3',
    databaseURL: 'https://pebo-task-manager-767f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pebo-task-manager-767f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFShmvfxluFtqhyTD3y0DlOKEAQqwOumA',
    appId: '1:646915822892:ios:79475fdbc1b64558554889',
    messagingSenderId: '646915822892',
    projectId: 'pebo-task-manager-767f3',
    databaseURL: 'https://pebo-task-manager-767f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pebo-task-manager-767f3.firebasestorage.app',
    iosClientId: '646915822892-d1oc4cq6a6sf8m74fah3hvrb23u7h3o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.peboSetupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFShmvfxluFtqhyTD3y0DlOKEAQqwOumA',
    appId: '1:646915822892:ios:79475fdbc1b64558554889',
    messagingSenderId: '646915822892',
    projectId: 'pebo-task-manager-767f3',
    databaseURL: 'https://pebo-task-manager-767f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pebo-task-manager-767f3.firebasestorage.app',
    iosClientId: '646915822892-d1oc4cq6a6sf8m74fah3hvrb23u7h3o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.peboSetupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2ZcQrnmrsisUCjywsfEYn4pR69PZCrpE',
    appId: '1:646915822892:web:a7d2a28febc69da7554889',
    messagingSenderId: '646915822892',
    projectId: 'pebo-task-manager-767f3',
    authDomain: 'pebo-task-manager-767f3.firebaseapp.com',
    databaseURL: 'https://pebo-task-manager-767f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pebo-task-manager-767f3.firebasestorage.app',
    measurementId: 'G-8ETRRGTZZP',
  );

}